server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql:///drools?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    tomcat:
      max-idle: 10
      min-idle: 0
      max-active: 20
    username: root

