package rules
import com.gu.drools.fosunhealth.entity.*;
import com.gu.drools.fosunhealth.util.*;
import java.util.*;
import java.text.*;
import java.lang.*;
import com.alibaba.fastjson.*;
dialect  "mvel"

/*rule "NPGC0020"
when
    个人保单 : Lccont( )
    直接被保人 : Lcinsured( ) from 个人保单.lcinsuredList
    eval( 直接被保人.birthday== 个人保单.cvaliDate )
then
    ruleInfo("返回信息");
end*/


rule "NPGC0020"
when
    返回信息:UWDto()
    个人保单 : Lccont( )
    直接被保人 : Lcinsured( ) from 个人保单.lcinsuredList
    eval( 直接被保人.birthday== 个人保单.cvaliDate )
then
    ruleInfo(返回信息,drools.getRule().getName())
end

 function void ruleInfo(UWDto var0,String name){
	var0.addVerify("年龄不正确",name);
}
