package rules
import com.gu.drools.fosunhealth.entity.*;
import com.gu.drools.fosunhealth.util.*;
import java.util.*;
import java.text.*;
import java.lang.*;
import com.alibaba.fastjson.*;
dialect  "java"

/*rule "NPGC0020"
when
    个人保单 : Lccont( )
    直接被保人 : Lcinsured( ) from 个人保单.lcinsuredList
    eval( 直接被保人.birthday== 个人保单.cvaliDate )
then
    ruleInfo("返回信息");
end*/


rule "NPGC0020"
when
    返回信息:UWDto()
    个人保单 : Lccont( )
    eval( PublicStaticFunctions.getname() != 个人保单.getContNo())
then
    System.out.println("success");
end


